steps:
# - name: 'gcr.io/$PROJECT_ID/ngcontainer'
#   args: ['npm', 'install']
# - name: 'gcr.io/$PROJECT_ID/ngcontainer'
#   args: ['npm', 'run', 'test:ci']
# - name: 'gcr.io/$PROJECT_ID/ngcontainer'
#   args: ['npm', 'run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/xlayers', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/xlayers']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/$PROJECT_ID-staging'
  - 'xlayers=gcr.io/$PROJECT_ID/xlayers'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=xlayers'
images:
  - 'gcr.io/$PROJECT_ID/xlayers'
  - 'gcr.io/$PROJECT_ID/xlayers:latest'