steps:
  - name: 'gcr.io/cross-xlayers/ngcontainer'
    entrypoint: 'npm'
    args: ['install']

  - name: 'gcr.io/cross-xlayers/ngcontainer'
    entrypoint: 'npm'
    args: ['run', 'test:ci']

  - name: 'gcr.io/cross-xlayers/ngcontainer'
    entrypoint: 'npm'
    args: ['run', 'build', '--', '--output-path', 'dist/html']
    env:
      - 'BUILD_ID=$BUILD_ID'

  # Build snapshot images and push them to Cloud Registry

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/xlayers:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/xlayers:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/xlayers:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/xlayers:latest']

  # Patch a new Ingress ressource for the build $SHORT_SHA

  - name: 'gcr.io/cross-xlayers/ngcontainer'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        perl -pe "s/_SHORT_SHA_/$SHORT_SHA/g" scripts/cloudbuild/xlayers.template.yaml > xlayers.$SHORT_SHA.yaml

  # Apply a new Ingress ressource for the build $SHORT_SHA

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'xlayers.$SHORT_SHA.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-small'

    # Send the preview domain to the issue thread on GitHub

  - name: 'gcr.io/cross-xlayers/ngcontainer'
    args:
      - |
        query='{
            search(first: 1, type: ISSUE, query: "type:pr repo:xlayers/xlayers $COMMIT_SHA") {
                nodes {
                ... on PullRequest {
                    id
                    }
                }
            }
        }'
        body='Preview: https://xlayers-$SHORT_SHA.angular.run'
        subjectId=$(curl -s -X POST \
            --url 'https://api.github.com/graphql?access_token=$$GITHUB_ACCESS_TOKEN' \
            --header 'content-type: application/json' \
            --data '{ "query": "$query" }' | python -c 'import sys, json; print json.load(sys.stdin)["data"]["search"]["nodes"][0]["id"]')

        curl -X POST \
            --url 'https://api.github.com/graphql?access_token=$$GITHUB_ACCESS_TOKEN' \
            --header 'content-type: application/json' \
            --data '{ "query": "mutation AddCommentToIssue { addComment(input: { subjectId: \"$subjectId\",body: \"$body\"}) { clientMutationId }}" }'

    secretEnv: ['GITHUB_ACCESS_TOKEN']

images:
  - 'gcr.io/$PROJECT_ID/xlayers:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/xlayers:latest'

secrets:
  - kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/GITHUB_ACCESS_TOKEN/cryptoKeys/GITHUB_ACCESS_TOKEN
    secretEnv: 'CiQAIttKJCkxPmE0ERPWC8ZmeCFu+FhzcLQofsCCU1Mb9LMDKS8SUQCXwYbhw8R19NiubGBr6xNfWuSht5aQRY53ICIJc2/y0bMKTtlLhk5FptsBNeEW6pbpv0itfQMwcWa+ts+gUw8VWzBUmrSPz76N5MpjFqsJxQ=='
