steps:
- name: gcr.io/cloud-builders/bazel
  args: ['run', '@yarn//:yarn']
- name: gcr.io/cloud-builders/bazel
  args: ['build', '//...']
# - name: gcr.io/cloud-builders/bazel
#   args: ['test', '//...']
# Push the image.
images: ['gcr.io/$PROJECT_ID/xlayers']