steps:
- name: 'angular/ngcontainer:latest'
  args: ['npm', 'install']
- name: 'angular/ngcontainer:latest'
  args: 
  - 'xvfb-run'
  - '-a'
  - 'npm'
  - 'run'
  - 'test:ci'
- name: 'angular/ngcontainer:latest'
  args: ['npm', 'run', 'build']
  env:
    - 'ENV=production'
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/$PROJECT_ID-staging'
  - 'xlayers=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=xlayers'
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'