apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-{{SHORT_SHA}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/hsts: "true"
    nginx.org/hsts-include-subdomains: "true"
spec:
  rules:
  - host: {{SHORT_SHA}}.angular.run
    http:
      paths:
        - path: /
          backend:
            serviceName: xlayers-{{SHORT_SHA}}
            servicePort: 80
  tls:
  - secretName: nginx-ingress-nginx-secret
    hosts:
    - '*.angular.run'
---
apiVersion: v1
kind: Service
metadata:
  name: xlayers-{{SHORT_SHA}}
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: xlayers-{{SHORT_SHA}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xlayers-{{SHORT_SHA}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xlayers-{{SHORT_SHA}}
  template:
    metadata:
      labels:
        app: xlayers-{{SHORT_SHA}}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: xlayers
          image: gcr.io/cross-xlayers/xlayers:{{SHORT_SHA}}
          ports:
          - containerPort: 80
          imagePullPolicy: Always